# Generated by Django 3.2 on 2022-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('subject', models.CharField(choices=[('CONSTRUCTION', 'Construction General'), ('SAFETY', 'Safety')], max_length=250, verbose_name='subject')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
