# Generated by Django 3.2 on 2022-11-02 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%Y/%m/%d/', verbose_name='image')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('short_description', models.CharField(help_text='Give a short description to this project. 500 characters is given', max_length=500, verbose_name='short description')),
                ('client', models.CharField(max_length=150, verbose_name='client')),
                ('architect', models.CharField(max_length=150, verbose_name='architect')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('size', models.PositiveIntegerField(default=0, help_text='Square feet (sqft)', verbose_name='size')),
                ('year_completed', models.PositiveIntegerField(verbose_name='year completed')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
