# Generated by Django 3.2 on 2022-11-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Link to project'),
        ),
    ]
