# Generated by Django 3.2 on 2022-11-04 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='full name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='author/%Y/%m/%d/')),
                ('short_description', models.CharField(blank=True, help_text='Only 200 characters allowed', max_length=500, null=True, verbose_name='short description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Only 200 characters allowed', max_length=200, verbose_name='title')),
                ('thumbnail', models.ImageField(upload_to='post/%Y/%m/%d/', verbose_name='thumbnail')),
                ('detail', tinymce.models.HTMLField(verbose_name='detail')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='author')),
                ('category', models.ForeignKey(default='miscellanous', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-date_created'],
            },
        ),
    ]
