# Generated by Django 3.2 on 2022-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='designation'),
        ),
    ]
