# Generated by Django 3.2 on 2022-11-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
