# Generated by Django 3.2 on 2022-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='year completed'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
