# Generated by Django 3.2 on 2022-11-09 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20221107_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, help_text='Please use this format: November 2021', max_length=200, null=True, verbose_name='date')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is active')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='year_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='news.archive', verbose_name='year completed'),
        ),
    ]
