# Generated by Django 3.2 on 2022-11-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20221109_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
