# Generated by Django 3.2 on 2022-11-01 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Only 200 characters allowed', max_length=200, verbose_name='title')),
                ('overview', models.CharField(help_text='Short description about this service. Only 500 characters allowed', max_length=500, verbose_name='overview')),
                ('icon', models.ImageField(upload_to='services/icon-image/%Y/%m/', verbose_name='icon')),
                ('thumbnail', models.ImageField(upload_to='services/thumbnail/%Y/%m/', verbose_name='thumbnail')),
                ('detail', models.TextField(verbose_name='detail')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('slug', models.SlugField(max_length=250, verbose_name='slug')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='e.g: John Doe', max_length=150, verbose_name='full name')),
                ('designation', models.CharField(max_length=50, verbose_name='designation')),
                ('avatar', models.ImageField(upload_to='team/%Y/%m/', verbose_name='avatar')),
                ('short_description', models.CharField(help_text='Only 100 characters allowed', max_length=100, verbose_name='short description')),
                ('facebook_link', models.CharField(blank=True, max_length=1500, null=True, verbose_name='facebook link')),
                ('twitter_link', models.CharField(blank=True, max_length=1500, null=True, verbose_name='twitter link')),
                ('linkedIn_link', models.CharField(blank=True, max_length=1500, null=True, verbose_name='linkedIn link')),
                ('googleplus_link', models.CharField(blank=True, help_text='e.g: johndoe567@gmail.com', max_length=1500, null=True, verbose_name='google+ link')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='e.g: John Doe', max_length=150, verbose_name='full name')),
                ('designation', models.CharField(max_length=50, verbose_name='designation')),
                ('avatar', models.ImageField(upload_to='testimonial/%Y/%m/', verbose_name='avatar')),
                ('short_message', models.CharField(help_text='Only 150 characters allowed', max_length=150, verbose_name='short message')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
